baseURL = 'https://pronchakov.github.com/'
languageCode = 'en-us'
title = 'laboratory journal'
theme = 'nightfall'

[menu]
[[menu.header]]
name = "java"
weight = 0
url = "/java"

[[menu.header]]
name = "3d"
weight = 1
url = "/3d"

[[menu.header]]
name = "uav"
weight = 2
url = "/uav"

[params]
author = "laboratory journal"
user = "pronchakov"
hostname = "github.io"
homedir = "/home/maniak"
published = true
readingTime = false

[[params.social]]
key = 0
name = "github"
url = "https://github.com/pronchakov"

[[params.social]]
key = 1
name = "email"
url = "mailto:artem.pronchakov@gmail.com"